### ISSUE TITLE
there is an issue with fx default param loading

### ISSUE THREAD

**Issue by spiricom** [spiricom/Electrobass_JUCE#44]
for instance - start a blank preset. Then add Hardclip as the first effect. Look at the waveform. It's clipped to be only positive values. That's the behavior if offset is set to zero. But the knob shows offset set to .5
Change the offset knob and then bring it back to .5 and now the hardclip is centered around zero as it should be. So it displays the correct knob value but doesn't load it when the effect is first loaded.

**Comment by davispolito** [comment]
asdf
